swarm:
  bind:
    address: 192.168.25.100 #home desk
  network:
    socket-binding-groups:
      standard-sockets:
        socket-bindings:
          activemq:
            port: 61616
  messaging-activemq:
    servers:
      default:
        jms-queues:
          mediation-queue:
            entries:
              entry: "java:/jms/queue/mediation-queue java:/jboss/exported/jms/queue/mediation-queue"
        security-enabled: false
        remote-acceptors:
            netty-acceptor:
              socket-binding: activemq
        remote-connectors:
            netty-connector:
              socket-binding: activemq
        http-connectors:
          http-connector:
            socket-binding: http
            endpoint: http-acceptor
        http-acceptors:
          http-acceptor:
            http-listener: default
        jmx-management-enabled: true
#--- Consumer config
  messaging:
    remote:
      name: geoexplo-mq
      host: 192.168.25.100
      port: 61616
      jndi-name: java:/jms/geoexplo-mq
  remote: false
