swarm:
  bind:
    address: 192.168.25.100
  port:
    offset: 200
  messaging:
    remote:
      name: geoexplo-mq
      host: 192.168.25.100
      port: 61616
      jndi-name: java:/jms/geoexplo-mq
  remote: true